service: aws-labs-nest-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: src/main.handler
    events:
      - http:
          method: get
          path: /

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
