service: aws-labs-express-typescript-puppeteer

provider:
  name: aws
  runtime: nodejs12.x

  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:22

functions:
  app:
    handler: handler.app
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
