service: aws-labs-express-typescript-plugin

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
